angular.module('app').run(['$templateCache',function($templateCache){  'use strict';

  $templateCache.put('src/view/login.html',
    "<div class=\"secHeader\"><h1>State thy name and ye shall pass</h1><p>Not a member yet? <a ui-sref=\"registration\">Register</a> now — it's fun and easy!</p></div><div class=\"loginReg clear\"><div class=\"userForm fl\"><div class=\"loginForm\" ng-controller=\"LoginController\"><form name=\"loginForm\" id=\"loginForm\"><div class=\"formControl\"><input type=\"text\" class=\"inputControl\" name=\"userName\" ng-model=\"data.userName\" placeholder=\"Username\" validate rel=\"required:1000\"> <span class=\"errLbl\"></span></div><div class=\"formControl\"><input type=\"password\" class=\"inputControl\" name=\"userPwd\" ng-model=\"data.userPwd\" placeholder=\"Password\" validate rel=\"required:1000\"> <span class=\"errLbl\"></span></div><div class=\"btn clear\"><div class=\"remember fl\"><input type=\"checkbox\" name=\"remember\" id=\"remember\"><label for=\"remember\">Remember me</label></div><input type=\"submit\" name=\"reg\" value=\"Login\" class=\"fr\" ng-click=\"onSubmit($event)\" ng-class=\"{'btn-dis':(!data.userName || !data.userPwd),'btn-active':(data.userName && data.userPwd)}\"></div></form></div></div><div class=\"verticalSep fl\"><span>or</span></div><div class=\"social fl\"><div class=\"fb\"><a href=\"javascript:void(0);\">Login with Facebook</a></div><div class=\"twt\"><a href=\"javascript:void(0);\">Login with Twitter</a></div></div></div>"
  );


  $templateCache.put('src/view/registration.html',
    "<div class=\"secHeader\"><h1>Join Tango today.</h1><p>It's free and always will be.</p></div><div class=\"loginReg clear\"><div class=\"userForm fl\"><div class=\"regForm\" ng-controller=\"RegistrationController\"><form name=\"regForm\" id=\"regForm\"><div class=\"formControl\"><input type=\"text\" class=\"inputControl\" name=\"userEmail\" ng-model=\"data.email\" placeholder=\"Email Address\" validate rel=\"required:1000;email:1001\" data-success=\"1002\"> <span class=\"errLbl\"></span></div><div class=\"formControl\"><input type=\"text\" class=\"inputControl\" name=\"userName\" ng-model=\"data.userName\" placeholder=\"Username\" validate rel=\"required:1000;userName:1003\" data-success=\"1000\"> <span class=\"errLbl\"></span></div><div class=\"formControl\"><input type=\"password\" class=\"inputControl\" name=\"userPwd\" ng-model=\"data.userPwd\" placeholder=\"Password\" validate rel=\"required:1000\" data-success=\"1002\"> <span class=\"errLbl\"></span></div><div class=\"formControl\"><input type=\"password\" class=\"inputControl\" name=\"userPwdMatch\" ng-model=\"data.userPwdMatch\" placeholder=\"Confirm Password\" validate rel=\"required:1000;match:1002\" data-success=\"1001\" data-match=\"data.userPwd\"> <span class=\"errLbl\"></span></div><div class=\"formControl\" ng-class=\"{success:data.sex}\"><select ng-model=\"data.sex\" validate rel=\"required:1000\" data-success=\"\"><option value=\"\" disabled=\"disabled\" selected=\"selected\" hidden>Sex</option><option ng-repeat=\"val in sexDD\" value=\"{{val.id}}\">{{val.name}}</option></select><input type=\"hidden\" name=\"sex\" ng-model=\"data.sex\" validate rel=\"required:1000\"> <span class=\"errLbl\"></span></div><p class=\"termAndCon\">By clicking Register, you agree to our <a href=\"javascript:void(0);\">Terms</a> and that you have read our <a href=\"javascript:void(0);\">Data Use Policy</a>, including our <a href=\"javascript:void(0);\">Cookie Use</a>.</p><div class=\"btn submit\"><input type=\"submit\" name=\"reg\" value=\"Register\" class=\"fr\" ng-click=\"onSubmit($event)\" ng-class=\"{'btn-dis':(!data.email || !data.userName || !data.userPwd || !data.userPwdMatch ||  !data.sex),'btn-active':(data.email && data.userName && data.userPwd && data.userPwdMatch &&  data.sex)}\"></div></form></div></div><div class=\"verticalSep fl\"><span>or</span></div><div class=\"social fl\"><div class=\"fb\"><a href=\"javascript:void(0);\">Register with Facebook</a></div><div class=\"twt\"><a href=\"javascript:void(0);\">Register with Twitter</a></div></div></div>"
  );


  $templateCache.put('src/view/view.html',
    "<p>iiiiiiiiii</p>"
  );
}]);